(function(back){
  const S=require("Storage"),F="lifemon.json",ST="lifemon.state.json",L="lifemon.log";
  const D={stillG:.020,moveG:.035,baroSlowSec:15,baroFastStillSec:2,hrmStillSec:10,tempStillSec:15,tempIntervalSec:3,wearTempC:28,placedZMin:.85,placedStillSec:60,stairDispM:.30,integDeadband:.12,baroStableDeltaM:.20,stairStableSec:5,elevatorStableSec:15,fastMaxSec:120,minHeightM:.40,hrmSampleSec:10,hrmBlockMin:5,hrmConfidence:90,batteryTargetPct:10,batteryWarnHours:3,batteryWindowHours:6};
  let c=Object.assign({},D,S.readJSON(F,1)||{});
  function save(){S.writeJSON(F,c);if(global.LIFEMON&&global.LIFEMON.reloadSettings)global.LIFEMON.reloadSettings();}
  function f1(v){return v.toFixed(1)} function f2(v){return v.toFixed(2)} function f3(v){return v.toFixed(3)}
  function ts(ms){if(!ms)return "-";let d=new Date(ms);return ("0"+d.getHours()).substr(-2)+":"+("0"+d.getMinutes()).substr(-2);}
  function noop(){}
  function status(){let p=S.readJSON(ST,1)||{},s=p.summary||{},v=global.LIFEMON&&global.LIFEMON.getState?global.LIFEMON.getState():null,w=v?v.wear:(s.wear||p.wear||"unknown"),b=v?v.batteryPct:(p.batteryPct===undefined?E.getBattery():p.batteryPct),e=v?v.batteryEstimateHours:p.batteryEstimateHours,h=v&&v.hrmPartial!==null?v.hrmPartial:s.lastHR,m={"":{"title":"Life data"},"< Back":main};m["Wear: "+w]=noop;m["Temp: "+(s.lastTemp===undefined?"-":s.lastTemp+" C")]=noop;m["HR: "+(h===null||h===undefined?"-":h+" bpm")]=noop;m["Stair +: "+(s.stairsUp||0)+"m"]=noop;m["Stair -: "+(s.stairsDown||0)+"m"]=noop;m["Lift +: "+(s.elevatorUp||0)+"m"]=noop;m["Lift -: "+(s.elevatorDown||0)+"m"]=noop;m["Battery: "+b+"%"]=noop;m["To "+c.batteryTargetPct+"%: "+(e===null||e===undefined?"?":e.toFixed(1)+"h")]=noop;if(s.lastEvent)m["Last "+ts(s.lastEventTime)+" "+s.lastEvent]=noop;E.showMenu(m);}
  function recent(){let x=S.read(L)||"",a=x.trim()?x.trim().split("\n"):[];if(a.length>12)a=a.slice(-12);let m={"":{"title":"Recent data"},"< Back":main};if(!a.length)m["No data"]=noop;for(let i=a.length-1,j=1;i>=0;i--,j++){let p=a[i].split(","),t=ts(parseInt(p[0],10)),z=p[1]==="H"?t+" HR "+p[2]:p[1]==="S"?t+" stair "+p[2]+"m":p[1]==="E"?t+" lift "+p[2]+"m":p[1]==="W"?t+" "+p[2]+" "+p[3]+"C":t+" "+p[1]+" "+p[2];m[j+" "+z]=noop;}E.showMenu(m);}
  function motion(){E.showMenu({"":{"title":"Motion"},"< Back":main,"Still g":{value:c.stillG,min:.005,max:.08,step:.005,format:f3,onchange:v=>{c.stillG=v;save();}},"Move g":{value:c.moveG,min:.01,max:.12,step:.005,format:f3,onchange:v=>{c.moveG=v;save();}},"Stair disp":{value:c.stairDispM,min:.1,max:1,step:.05,format:v=>f2(v)+"m",onchange:v=>{c.stairDispM=v;save();}},"Int deadband":{value:c.integDeadband,min:.02,max:.5,step:.02,format:v=>f2(v)+"m/s2",onchange:v=>{c.integDeadband=v;save();}}});}
  function baro(){E.showMenu({"":{"title":"Barometer"},"< Back":main,"Slow sec":{value:c.baroSlowSec,min:5,max:60,step:5,onchange:v=>{c.baroSlowSec=v;save();}},"Fast after":{value:c.baroFastStillSec,min:1,max:10,step:1,format:v=>v+"s",onchange:v=>{c.baroFastStillSec=v;save();}},"Stable dH":{value:c.baroStableDeltaM,min:.05,max:1,step:.05,format:v=>f2(v)+"m",onchange:v=>{c.baroStableDeltaM=v;save();}},"Stair stable":{value:c.stairStableSec,min:2,max:30,step:1,format:v=>v+"s",onchange:v=>{c.stairStableSec=v;save();}},"Lift stable":{value:c.elevatorStableSec,min:5,max:30,step:1,format:v=>v+"s",onchange:v=>{c.elevatorStableSec=v;save();}},"Min height":{value:c.minHeightM,min:.1,max:3,step:.1,format:v=>f1(v)+"m",onchange:v=>{c.minHeightM=v;save();}},"FAST max":{value:c.fastMaxSec,min:30,max:300,step:10,format:v=>v+"s",onchange:v=>{c.fastMaxSec=v;save();}}});}
  function hrm(){E.showMenu({"":{"title":"Heart rate"},"< Back":main,"Start still":{value:c.hrmStillSec,min:3,max:60,step:1,format:v=>v+"s",onchange:v=>{c.hrmStillSec=v;save();}},"Sample":{value:c.hrmSampleSec,min:5,max:60,step:5,format:v=>v+"s",onchange:v=>{c.hrmSampleSec=v;save();}},"Average":{value:c.hrmBlockMin,min:1,max:15,step:1,format:v=>v+"min",onchange:v=>{c.hrmBlockMin=v;save();}},"Confidence":{value:c.hrmConfidence,min:20,max:100,step:5,format:v=>v+"%",onchange:v=>{c.hrmConfidence=v;save();}}});}
  function wear(){E.showMenu({"":{"title":"Wear detect"},"< Back":main,"Start still":{value:c.tempStillSec,min:5,max:60,step:1,format:v=>v+"s",onchange:v=>{c.tempStillSec=v;save();}},"Temp gap":{value:c.tempIntervalSec,min:1,max:10,step:1,format:v=>v+"s",onchange:v=>{c.tempIntervalSec=v;save();}},"Wear temp":{value:c.wearTempC,min:20,max:38,step:.5,format:v=>f1(v)+"C",onchange:v=>{c.wearTempC=v;save();}},"Placed |z|":{value:c.placedZMin,min:.5,max:1,step:.05,format:f2,onchange:v=>{c.placedZMin=v;save();}},"Placed after":{value:c.placedStillSec,min:15,max:300,step:15,format:v=>v+"s",onchange:v=>{c.placedStillSec=v;save();}}});}
  function battery(){E.showMenu({"":{"title":"Battery"},"< Back":main,"Target":{value:c.batteryTargetPct,min:5,max:30,step:1,format:v=>v+"%",onchange:v=>{c.batteryTargetPct=v;save();}},"Warn before":{value:c.batteryWarnHours,min:1,max:12,step:1,format:v=>v+"h",onchange:v=>{c.batteryWarnHours=v;save();}},"Fit window":{value:c.batteryWindowHours,min:2,max:24,step:1,format:v=>v+"h",onchange:v=>{c.batteryWindowHours=v;save();}}});}
  function reset(){E.showPrompt("Restore all thresholds?",{title:"Life Monitor"}).then(ok=>{if(ok){c=Object.assign({},D);save();}main();});}
  function clear(){E.showPrompt("Delete Life Monitor history?",{title:"Life Monitor"}).then(ok=>{if(ok){S.erase(L);S.erase(ST);}main();});}
  function main(){E.showMenu({"":{"title":"Life Monitor"},"< Back":back,"Current / Today":status,"Recent data":recent,"Motion":motion,"Barometer":baro,"Heart rate":hrm,"Wear detect":wear,"Battery":battery,"Reset thresholds":reset,"Clear history":clear});}
  main();
})